# This is a basic workflow to help you get started with Actions

name: AutoGerber

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    branches: [ main ]
    paths:
    - '**.sch'
    - '**.kicad_pcb'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3.1
      with:
      # Required - kibot config file
        config: JLC.kibot.yaml
      # optional - prefix to output defined in config
        dir: Core/outputs
      # optional - schematic file
        schema: '*USB.sch'
      # optional - PCB design file
        board: '*USB.kicad_pcb'
      # optional - verbose output info
        verbose: 0
    - uses: nerdyscout/kicad-exports@v2.3.1
      with:
      # Required - kibot config file
        config: JLC.kibot.yaml
      # optional - prefix to output defined in config
        dir: Front/outputs
      # optional - schematic file
        schema: '*Front.sch'
      # optional - PCB design file
        board: '*Front.kicad_pcb'
      # optional - verbose output info
        verbose: 0
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
